# config/packages/ux_icons.yaml
ux_icons:
    # The local directory where icons are stored
    icon_dir: "%kernel.project_dir%/assets/icons"

    # Default attributes to add to all icons
    default_icon_attributes:
        fill: currentColor
        "font-size": "1.25em"
        class: icon

    # Icon aliases (alias => icon name)
    aliases:
        dots: "clarity:ellipsis-horizontal-line"
        "tabler:save": "tabler:device-floppy"

    # Configuration for the "on demand" icons powered by Iconify.design
    iconify:
        enabled: true

        # Whether to use the "on demand" icons powered by Iconify.design
        on_demand: true

        # The endpoint for the Iconify API
        endpoint: "https://api.iconify.design"

    # Whether to ignore errors when an icon is not found
    ignore_not_found: false

    # Icon sets configuration, array of prefix => icon set configuration
    icon_sets:
        # Icon set for "flags", can be used like this: ux_icon('flags:fr')
        flags:
            # It can either be mapped to a local directory...
            path: "%kernel.project_dir%/assets/images/flags"

            # ... or to an existing icon set identifier
            alias: "lucide"

            # Override the default attributes (default_icon_attributes) for this icon set
            icon_attributes:
                class: "flag" # Replace the default class
                stroke: "none" # Add a new attribute
                fill: false # Use "false" to remove a default attribute
